Resources
novuscore/NovusCore-World pull request #1
Opened 2022-03-26 21:12 UTC by TheGrimsey

- Add player tree (kd-tree containing just player entities)
- Give players GameEntityFlagPlayer flag component and use that to update players in UpdateEntitySystem
- Give players resource,attribute,ratings components
- Temporary creature positon sync.

2022-04-03 13:53 UTC, NixAJ requested changes

2022-04-03 13:53 UTC, NixAJ commented on src/ECS/Components/Singletons/MapSingleton.h
> +	Tree2D& GetEntityTree() { return _playerTree; };
Looks like you made a typo here, I'm assuming GetEntityTree should return "_entityTree" and not "_playerTree"

2022-04-03 13:53 UTC, NixAJ commented on src/ECS/Systems/SpawnPlayerSystem.cpp
> +            resources.resources[static_cast<u8>(EntityResourceType::HEALTH)] = 100.f;
Would it make sense given the usage here to rename the members of EntityResources to "current", "max"?

2022-04-03 13:53 UTC, NixAJ commented on src/ECS/Systems/UpdateEntityPositionSystem.cpp
> +                for (entt::entity seenEntity : seenEntities)
I personally prefer if we could move this back to a standard "for (u32 i..." and grab the entity by indexing into the vector.

2022-04-03 13:53 UTC, NixAJ commented on src/EngineLoop.cpp
> +        {
Please fix indentation here

2022-04-03 20:59 UTC, NixAJ requested changes

2022-04-03 20:59 UTC, NixAJ commented on src/ECS/Systems/UpdateEntityPositionSystem.cpp
> -                    if (!registry.valid(seenEntity) || !registry.all_of<GameEntityPlayerFlag>(seenEntity))
Define a variable at the top of the for loop and index once, and then reuse in the rest of the loop.

2022-05-29 21:54 UTC, Pursche approved these changes
This looks good. There is a slight concern over having to do "resources.current[static_cast<u8>(EntityResourceType::HEALTH)] = 100.f;", but we will look into a better way of doing this soon.

2022-05-29 21:55 UTC, merged